// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function UserGetAccount() {
  return window['go']['app']['App']['UserGetAccount']();
}

export function UserGetStatus() {
  return window['go']['app']['App']['UserGetStatus']();
}

export function UserIsLoggedIn() {
  return window['go']['app']['App']['UserIsLoggedIn']();
}

export function UserLogin(arg1, arg2) {
  return window['go']['app']['App']['UserLogin'](arg1, arg2);
}

export function UserLogout() {
  return window['go']['app']['App']['UserLogout']();
}
