// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function UserGetAccount():Promise<{[key: string]: any}>;

export function UserIsLoggedIn():Promise<boolean>;

export function UserLogin(arg1:string,arg2:string):Promise<boolean>;

export function UserLogout():Promise<void>;
