// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function UserGetAccount() {
  return window['go']['main']['App']['UserGetAccount']();
}

export function UserIsLoggedIn() {
  return window['go']['main']['App']['UserIsLoggedIn']();
}

export function UserLogin(arg1, arg2) {
  return window['go']['main']['App']['UserLogin'](arg1, arg2);
}
